title: "Vinnu Bhardwaj"

# Enable or disable the site search
search_enabled: true

# Set the search token separator for hyphenated-word search:
search_tokenizer_separator: /[\s/]+/

# Enable or disable heading anchors
heading_anchors: true

theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
color_scheme: test 
#search_enabled: false
plugins:
  - jekyll-seo-tag

use_math: true

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

